apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "600Mi"
            requests:
              memory: "300Mi"
          ports:
            - containerPort: 8080
          env:
            - name: JWT_BASE64_URL_ENCODED
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: jwt-base64-encode
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30999

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
data:
  # base64 encode of a base64url encoded string
  jwt-base64-encode: U0VsVVNFVlNSVWhQVjFsUFZVUlBTVTVIVkU5RVFWbEpTRTlRUlVWV1JWSlpWRWhKVGtkSlUwZFBUMFE=
