services:
  api-gateway-service:
    container_name: api-gateway
    build:
      context: .
      target: ${BUILD_TARGET:-dev}
    volumes:
      - ~/.m2:/root/.m2
      - ./:/app
    networks:
      - ms
    ports:
      - 8080:8080

networks:
  ms:
    external: true
