spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication_api
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
            - Method=POST
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}

        - id: rooms_api_get_requests
          uri: http://room-service:8080
          predicates:
            - Path=/api/rooms/**
            - Method=GET
          filters:
            - RewritePath=/api/rooms/(?<segment>.*), /rooms/${segment}

        - id: rooms_api_post_request
          uri: http://room-service:8080
          predicates:
            - Path=/api/rooms/
            - Method=POST
            - Header=Authorization, ^Bearer\s.*
          filters:
            - RewritePath=/api/rooms/, /rooms/
            - name: AuthenticationGateway