spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-methods:
              - GET
              - POST
              - OPTIONS
              - DELETE
            allowed-headers: "*"
            allowed-origins: "*"
        add-to-simple-url-handler-mapping: true

      routes:
        - id: authentication_api
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
            - Method=POST
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}

        - id: rooms_api_get_requests
          uri: http://room-service:8080
          predicates:
            - Path=/api/rooms/**
            - Method=GET
          filters:
            - RewritePath=/api/rooms/(?<segment>.*), /rooms/${segment}

        - id: rooms_api_post_request
          uri: http://room-service:8080
          predicates:
            - Path=/api/rooms/
            - Method=POST
            - Header=Authorization, ^Bearer\s.*
          filters:
            - RewritePath=/api/rooms/, /rooms/
            - name: AuthenticationGateway

        - id: websocket_requests
          uri: http://message-service:8080
          predicates:
            - Path=/websocket/
            - Method=GET
            - Header=Upgrade, websocket
            - Header=Connection, Upgrade
          filters:
            - RewritePath=/websocket/, /rooms

        - id: discovery_api
          uri: http://discovery-service:8761
          predicates:
            - Path=/api/discovery/**
          filters:
            - StripPrefix=2

jwt:
  base64-url:
    encoded:
      secret-key: NUU2MTFFNDUxREI4MTc4N0RGNUY3NThGMEFBMUExQUQ=

server:
  error:
    include-stacktrace: never

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
