spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: authentication_api
          uri: http://auth-service:8080
          predicates:
            - Path=/api/auth/**
            - Method=POST
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/${segment}
